name: build
on:
    push:
        branches:
            - main
jobs:
    set-version:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.set-version.outputs.version }}
        steps:
            -   uses: actions/checkout@v3
            -   name: set version
                id: set-version
                run: |
                    echo Faking a Semantic Version
                    echo ::set-output name=version::1.$(date "+%Y%m%d%H%M%S")
    build:
        runs-on: ubuntu-latest
        needs: [set-version]
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v2
                with:
                    distribution: 'temurin'
                    java-version: '17.x'
                    cache: 'gradle'
            -   name: test and build
                run: ./gradlew build -Pversion=${{ needs.set-version.outputs.version }} -Prepository=${{ github.repository }}
            -   name: upload dist
                uses: actions/upload-artifact@v3
                with:
                    name: binary
                    path: |
                      build/libs/app.jar
                      rr
                    if-no-files-found: error
    snyk:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Gradle vulnerability check
                uses: snyk/actions/gradle@master
                env:
                    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
                with:
                    args: --org=tbd-ty7 --fail-on=all --project-name=bomlo-cli --configuration-matching='^runtimeClasspath'
                    command: monitor
    release:
        if: ${{ github.ref == 'refs/heads/main' }}
        needs:
            - set-version
            - build
            - snyk
        runs-on: ubuntu-latest
        steps:
            - name: Checkout latest code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: Download binary from build
              uses: actions/download-artifact@v3
              with:
                  name: binary
            - name: Create Release Draft
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                    gh release create ${{ needs.set-version.outputs.version }} \
                    --generate-notes \
                    --title "${{ needs.set-version.outputs.version }}" \
                    ./build/libs/app.jar ./rr
